### ISSUE TITLE
[請款]: 2023 Bing 協助社群費用

### ISSUE THREAD

**Issue by NIC619** [EtherTW/accounting#10]
### 暱稱

Nic

### 類型

已經支出

### 帳務處理人是否認識你

- [X] 帳務處理人可以從暱稱知道如何聯絡我

### 代幣種類

ETH

### 金額

2.90625

### Ethereum 主網帳號地址或 ENS

0x9E10a814710C2B1f5a2477C2Eca4d70a32F3aFe5

### 請款項目

| 項目         | 用途說明                     | 金額 (TWD) |
| ------------ | ---------------------------- | ---------- |
| TEM 線上線下演講 | 包含尋找聯絡講者、尋找準備場地、活動宣傳、相關文宣、主持、全程錄影並上傳至 TEM 頻道 | |
| TEM 聚會 | 包含找場地及準備聚會物品。| |
| TEM Medium 審稿及發文管理 | 在有新投稿時評估並尋找適合的審稿人，並追蹤審稿進度、聯絡投稿人，最後安排發文 | |
| COSCUP | 組織 COSCUP 的區塊鏈議程、尋找審稿人、管理審稿進度、聯絡投稿人，以及 COSCUP 當天負責管理人員、場地，確保演講順利進行 | |
| **總計**     |                              | 360,000 TWD    |

### 附件或其他補充資訊

金額為 360,000 TWD 等值之 ETH
360000 ~= 11160 USD ~= 2.90625 ETH (1 ETH = 3840 USD)

**Comment by yurenju** [comment]
tx: https://etherscan.io/tx/0x49e72b3edc219d8e3946a653910995755f9417f5fe061d905eb0b017a7920a27
