### ISSUE TITLE
[請款]: TEM Grant - 社群活動報名平台 Survey

### ISSUE THREAD

**Issue by NIC619** [EtherTW/accounting#14]
### 暱稱

Nic

### 類型

預算

### 帳務處理人是否認識你

- [X] 帳務處理人可以從暱稱知道如何聯絡我

### 代幣種類

ETH

### 金額

200 USD

### Ethereum 主網帳號地址或 ENS

0x2A38D53165bEe3f9f88e3D783871bCF15D965f3b

### 請款項目

| 項目         | 用途說明                     | 金額 (USD) |
| ------------ | ---------------------------- | ---------- |
|   TEM Grant：社群活動報名平台 Survey          |     [Grant 產出](https://medium.com/taipei-ethereum-meetup/%E6%B4%BB%E5%8B%95%E5%B9%B3%E5%8F%B0%E7%9A%84%E6%B7%B1%E5%85%A5%E8%A7%A3%E6%9E%90-%E6%8E%A2%E7%B4%A2-luma-kktix-meetup-oveit-%E7%9A%84%E4%B8%96%E7%95%8C-60e7470e593d)                         |      200      |
| **總計**     |                              | 200 USD    |

### 附件或其他補充資訊

社群活動報名平台 Survey Grant 頁面：https://hackmd.io/@nic619/BJtETYIZA

**Comment by yurenju** [comment]
準備轉 0.057 ETH ~= 204 USD

![image](https://github.com/user-attachments/assets/d274edce-1cf2-44ce-a7d0-da5f524f64b8)
