### ISSUE TITLE
[請款]: 2023~2024 Meetup.com 支出

### ISSUE THREAD

**Issue by slothservice** [EtherTW/accounting#6]
### 暱稱

CC

### 類型

已經支出

### 帳務處理人是否認識你

- [X] 帳務處理人可以從暱稱知道如何聯絡我

### 代幣種類

DAI

### 金額

188.82

### Ethereum 主網帳號地址或 ENS

liangcc.eth

### 請款項目

| 項目         | 用途說明                     | 金額 (TWD) |
| ------------ | ---------------------------- | ---------- |
|  Jan 23, 2024 - Jul 23, 2024  | 62.94   USD | 2030 TWD  |
| Jul 23, 2023 - Jan 23, 2024  |  62.94   USD  |  2030 TWD |
| Jan 23, 2023 - Jul 23, 2023  |  62.94   USD  |  2030 TWD |
| **總計**     |                              | 6090 TWD    |

### 附件或其他補充資訊

如有任何其他需要補充的附件、資訊或說明，請在此處詳細記述。
[2023Jan-Jul.pdf](https://github.com/EtherTW/accounting/files/14955818/2023Jan-Jul.pdf)
[2023Jul-Jan.pdf](https://github.com/EtherTW/accounting/files/14955819/2023Jul-Jan.pdf)
[2024Jan-Jul.pdf](https://github.com/EtherTW/accounting/files/14955820/2024Jan-Jul.pdf)

**Comment by yurenju** [comment]
此筆請款跟 #7  一起送出了，連結於此：
https://app.safe.global/transactions/tx?safe=eth:0x3BB6938118bbc1e63e56ABB94dBa66570F4BB0d0&id=multisig_0x3BB6938118bbc1e63e56ABB94dBa66570F4BB0d0_0x040d05a056d849786406ed5d53cf1a132eb7b965fb65334fd6c4b6d75ba6f13f

會請其他 gnosis safe owner 協助簽章

**Comment by yurenju** [comment]
done
https://etherscan.io/tx/0x7404e1e729fec021e7b437556c1c1918b28dfd104ce7f7fa69084915b4115b31

**Comment by slothservice** [comment]
謝謝 @yurenju ，確認收到
