### ISSUE TITLE
[請款]: zk taipei 一年份的 luma 訂閱費用

### ISSUE THREAD

**Issue by yurenju** [EtherTW/accounting#7]
### 暱稱

yurenju

### 類型

預算

### 帳務處理人是否認識你

- [X] 帳務處理人可以從暱稱知道如何聯絡我

### 代幣種類

ETH

### 金額

0.271358859

### Ethereum 主網帳號地址或 ENS

0x0f6bB11061191CEb8d43e9a35Bf73fA00d8670C2

### 請款項目

| 項目         | 用途說明                     | 金額 (USD) |
| ------------ | ---------------------------- | ---------- |
| luma  | luma 一年份的訂閱費用，一個月 69 USD |  828 USD   |
|              |                              |            |
| **總計**     |                              | 828 USD   |

備註： [luma 每月費用](https://lu.ma/pricing) 為 69 USD，每年的費用為 69 * 12 = 828，2024-04-20 當下的 ETH 價格為 3051.31，所以：

```
69 * 12 / 3051.31 = 0.271358859 ETH
```

**Comment by oskarth** [comment]
Looks right, thank you!

**Comment by yurenju** [comment]
此筆請款跟 #6 一起送出了，連結於此：
https://app.safe.global/transactions/tx?safe=eth:0x3BB6938118bbc1e63e56ABB94dBa66570F4BB0d0&id=multisig_0x3BB6938118bbc1e63e56ABB94dBa66570F4BB0d0_0x040d05a056d849786406ed5d53cf1a132eb7b965fb65334fd6c4b6d75ba6f13f

會請其他 gnosis safe owner 協助簽章

**Comment by yurenju** [comment]
done
https://etherscan.io/tx/0x7404e1e729fec021e7b437556c1c1918b28dfd104ce7f7fa69084915b4115b31
